---
  - hosts: host-1
    sudo: yes
    name: play1
    tasks:
    - name: execute commad date
      command: date
    - name: execute script on server #descripted name of tasks
      script: test_script.sh
    - name: Installing nginx
      apt: name=nginx state=latest

---
- hosts: slave1 
  become: yes
  name: Installing apache2 on slave1 
  tasks:
    - name: Install apache2
      apt: name=apache2 state=latest

- hosts: slave2 
  become: yes
  name: Installing nginx on slave2 
  tasks:
    - name: installing nginx
      apt: name=nginx state=latest
